name: Update PDF List

on:
  push:
    paths:
      - 'orders/**'  # Trigger action when PDFs are added to the orders folder

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run PDF list update script
      run: |
        python update_pdf_list.py  # Path to your Python script

    - name: Commit changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add index.html
        git commit -m "Update PDF list"
        git push
